### ISSUE TITLE
Back-pressure and max concurrency etc

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#10]
(issue from @julz)
Questions to answer:

1. Do we want to allow a user to configure how many asynchronous messages we should process at once?
2. If so, how?
3. Do we want to allow a user to configure back pressure, i.e. throttling the rate at which we process messages from the queue in response to changing throughput in the workers
4. If so, how?

**Comment by beemarie** [comment]
TODO: Will these knobs be exposed to the user?

**Comment by AngeloDanducci** [comment]
Freezing the async issues to preserve the "what's next"
/lifecycle frozen
