### ISSUE TITLE
Customizable Retries

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#11]
original issue from @julz 

This needs some thought. How would we configure retries and allow users to configure retry policy? (Maybe there's a simpler first story here which is just a hard-coded/operator configurable retry policy)

**Comment by beemarie** [comment]
TODO: We would also want to retry even if this is not a customizable knob.

**Comment by AngeloDanducci** [comment]
Freezing the async issues to preserve the "what's next"
/lifecycle frozen
