### ISSUE TITLE
Update hack folder

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#16]
Update the hack folder with required files:
- presubmit-tests.sh
- update-deps.sh
- etc.

**Comment by AngeloDanducci** [comment]
Is this issue already satisfied?

Both presubmit-tests.sh and update-deps.sh seem to be complete with [this PR ](https://github.com/knative-sandbox/async-component/pull/23)

The knative.dev/hack folder is near identical to other sandbox projects but there are many more (optional?) scripts in the [github.com/knative/hack](https://github.com/knative/hack) project.

The top level hack folder for async component seems to have the minimum tools.go and update-deps.sh but this seems to vary in number of additional scripts from project to project.

@n3wscott may I ask your opinion as someone who has done heavy lifting on the knative hack project?
