### ISSUE TITLE
Should markIngressReady only happen if underlying ingress is ready?

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#32]
Comment from @julz Im guessing this should only happen if we reconciled the ingress successfully, and the ingress we created has gone ready. Im imagining we want to propagate all the conditions on the sub-ingress up to this ingress eventually?

https://github.com/knative-sandbox/async-component/pull/20#discussion_r512849417

**Comment by beemarie** [comment]
TODO: Confirm if this is a dupe

**Comment by AngeloDanducci** [comment]
Freezing the async issues to preserve the "what's next"
/lifecycle frozen
