### ISSUE TITLE
Confirm support for other networking layer options

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#39]
... not just Istio.

**Comment by beemarie** [comment]
Note: There are a couple of hard coded istio specific items in the `ingress.go` file:
```
	publicLBDomain         = "istio-ingressgateway.istio-system.svc.cluster.local"
	privateLBDomain        = "cluster-local-gateway.istio-system.svc.cluster.local"
```
and

```ingressClass := networkpkg.IstioIngressClassName```

I believe if you create an ingress for a different networking layer, such as contour or kourier then this should "just work"

**Comment by AngeloDanducci** [comment]
Proven to be working with kourier (and additional support if/when enabled) here https://github.com/knative-sandbox/async-component/pull/105

Hard coded istio items were made dynamic here, however if/when other ingresses are desired they will need to be uncommented or added to the list, see below for details. https://github.com/knative-sandbox/async-component/pull/104 

Support for additional load balancer domains was added [here](https://github.com/knative-sandbox/async-component/blob/main/pkg/reconciler/ingress/ingress.go#L57)

Ingress class is dynamic based on the environment, and will default to kourier if the environment one is not found to be in the accepted list of keys for load balancers [here](https://github.com/knative-sandbox/async-component/blob/main/pkg/reconciler/ingress/ingress.go#L67)

@maximilien recommending we close this.

**Comment by maximilien** [comment]
Ok closing as per your recommendation
