### ISSUE TITLE
Ensure knative serving and go conventions followed in project's structural organization

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#45]
See conversation here:
https://github.com/knative-sandbox/async-component/pull/41#pullrequestreview-531834547

**Comment by AngeloDanducci** [comment]
Did a comparison and we seem to be following conventions:

- [x] Small mains, unit tests for functionality (ingress/controller)
- [x] Using latest knative release dependencies for E2E tests in this PR https://github.com/knative-sandbox/async-component/pull/105
- [x] cmd/vendor/test/config/etc and general project layout follow standard Golang conventions
- [x] Pre submit tests are working and test-infra has unit/integration tests marked as required
- [x] No dependency on ytt for E2E tests

I couldn't find a document outlining other particular Knative conventions.  A new contributor guide is being discussed here [here](https://groups.google.com/g/knative-dev/c/vqol3xL7qAs) and [here](https://github.com/knative/docs/issues/4538) which may help add some detail to this in the future.

I think this looks good to close unless you have other input @maximilien

**Comment by maximilien** [comment]
Thanks for verifying @AngeloDanducci

Closing
