### ISSUE TITLE
Production ready Redis Source/Channel 

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#5]
If eventing provides a Redis Source, use that. Otherwise explore what it means for the backing storage to be production ready.

**Comment by aavarghese** [comment]
@beemarie https://github.com/knative-sandbox/eventing-redis. Leaving this here for eventing's Redis source link

**Comment by AngeloDanducci** [comment]
Freezing the async issues to preserve the "what's next"
/lifecycle frozen
