### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#62]
We need to test this component for throughput and performance.

**Comment by maximilien** [comment]
@duglin ^^^

**Comment by duglin** [comment]
We're looking at initially supporting about 1000 requests/second - and eventually hoping to slowly increase that over time. How long each request's processing time is will obviously vary, but for now we can assume about 5 seconds per request.

**Comment by maximilien** [comment]
@duglin can you clarify a bit the 1000 req/s so I can make sure I am measuring the correct places. Do you mean 1000 req/s submitted / queued from a user’s perspective (i.e., a client using `curl` for instance to invoke an async service). Thx

**Comment by duglin** [comment]
Yes 1000 rps submitted from the user. And then I would expect the async infra to generate outbound requests to the sink at a similar rate.

**Comment by maximilien** [comment]
OK thanks @duglin. Unlikely we will be close but good to have your needs clarified. Thx

**Comment by AngeloDanducci** [comment]
Here are some initial findings from the requests side.  I will open a PR to update the README with methodology used.

JMeter was used to generate load against the helloworld test application using 100 threads with 10 repeats each.

Cold start:
 
<img width="1154" alt="Screen Shot 2021-09-17 at 2 18 42 PM" src="https://user-images.githubusercontent.com/16545055/133836317-200c63f7-2f61-4698-a95d-4fcda8df7742.png">

Warm start:
<img width="1141" alt="Screen Shot 2021-09-17 at 2 26 08 PM" src="https://user-images.githubusercontent.com/16545055/133836392-beff3980-5db9-4bf2-a2cb-74ce11c16daa.png">

This matches similarly to previous runs where the calculated average was approximately 91.604ms.

Timespan of requests was performed within the desired window of 1s.
Final: 1631734724620
Initial: 1631734723516

May need to do some additional work to find the outbound requests to the sink (Step 6 in the design [here])(https://raw.githubusercontent.com/knative-sandbox/async-component/main/README-images/async-all-components.png)

@duglin ^

@aslom I also did an initial run of kperf testing - is measuring this outbound requests to the sink something your work on the new kperf update something that is feasible?

**Comment by maximilien** [comment]
Thanks for the update @AngeloDanducci. I look forward to the README update since that will allow others to replicate your results. Thx.

**Comment by duglin** [comment]
@AngeloDanducci thanks but can you show the graphs with a non-black background. It's really hard to read it.
Is this showing the throughput INTO the async queue?

**Comment by AngeloDanducci** [comment]
![Graph1](https://user-images.githubusercontent.com/16545055/134235277-fbfcba70-0325-42d5-80de-a8b2e43b31b5.png)
![Graph2](https://user-images.githubusercontent.com/16545055/134235282-fa437e27-a7a1-41af-877d-ec20476995de.png)

Yes, this is throughput into the async queue as measured by positive responses from the hello world application running with async.

**Comment by AngeloDanducci** [comment]
I performed some additional testing as the above was short large bursts which was reaching around 500 reqs/s with a positive response.

Here I let 100 threads hammer the service to see how sustained usage would be handled and we are over 1k reqs/sec but a small error rate.  The trend was upwards in terms of throughput so I don't think this has been pushed to its limit yet.
<img width="990" alt="Screen Shot 2021-09-27 at 2 59 00 PM" src="https://user-images.githubusercontent.com/16545055/134968701-720356d8-7008-4a87-b7df-90acba3d592c.png">
