### ISSUE TITLE
Explore use of a channel

### ISSUE THREAD

**Issue by bvennam** [knative-sandbox/async-component#63]
Explore the use of a channel rather than some pieces of the producer/consumer.

Rather than this layer dealing with the complexity that comes with durability, retries, etc. we could delegate that to the choice of a channel & potentially leverage the current investment that's going on in the eventing space.

One place to start would be to see if we can make this component work by replacing Redis with an in-memory channel. Once we try this out we can see where we're at as next steps.

**Comment by beemarie** [comment]
This might also address #6

**Comment by AngeloDanducci** [comment]
Freezing the async issues to preserve the "what's next"
/lifecycle frozen
