### ISSUE TITLE
Add integration tests for different ingresses 

### ISSUE THREAD

**Issue by maximilien** [knative-sandbox/async-component#91]
Add integration tests for the different configurable ingresses

**Comment by maximilien** [comment]
Cc: @AngeloDanducci

**Comment by AngeloDanducci** [comment]
Kourier and Istio are fully working using the integration test scripts on my local cluster.  
Happy path also verified for these two.

I also reached out to the community inquiring about best practices for setup/tear down if this is done sequentially.  
I saw inconsistent delete behavior in my cluster where a delete command would return successfully but a finalizer would be stuck for minutes or indefinitely if there was a problem.

Current Blockers:
Ambassador install fails in my cluster, I've reached out to in the net-ambassador channel, may need to open an issue.
Contour installs but shows as `Ingress Not Configured` - currently troubleshooting this.
